- hosts: all
  become: yes
  tasks:
    - name: add java PPA
      apt_repository:
        repo: "ppa:webupd8team/java"

    - name: accept oracle license
      debconf:
        name: "oracle-java8-installer"
        question: "shared/accepted-oracle-license-v1-1"
        value: "true"
        vtype: "select"

    - name: install jdk
      apt:
        name: "oracle-java8-installer"

    - name: Installing repo key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
        state: present
    - name: Adding the Jenkins repository
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present
    - name: Installing Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes
    - name: Start and enable the Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
    - name: Installing required packages
      apt: name={{ item }} state=present
      with_items:
        - git
        - phpunit
